version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tokio
    versions:
    - 1.0.1
    - 1.1.1
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.8
  - dependency-name: serde_derive
    versions:
    - 1.0.118
  - dependency-name: hyper
    versions:
    - 0.14.2
  - dependency-name: env_logger
    versions:
    - 0.8.2
  - dependency-name: log
    versions:
    - 0.4.11
  - dependency-name: byteorder
    versions:
    - 1.3.4
