language: rust
rust:
  - nightly
before_install:
  - curl -L https://github.com/google/protobuf/releases/download/v3.6.0/protoc-3.6.0-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf
  - cargo install protobuf-codegen && cargo install grpcio-compiler
env:
  - PATH=$HOME/protoc/bin:$PATH
addons:
  apt:
    update: true
