[log]
dir = ".log_head"

[replication]
server_addr = "0.0.0.0:4001"

[frontend]
server_addr = "0.0.0.0:4000"

[admin]
server_addr = "0.0.0.0:9000"

[management]
management_server_addr = "0.0.0.0:5000"
