[log]
dir = ".log_mid"

[replication]
server_addr = "0.0.0.0:4002"
upstream_addr = "0.0.0.0:4001"

[admin]
server_addr = "0.0.0.0:9001"

[frontend]
server_addr = "0.0.0.0:4104"

[management]
management_server_addr = "0.0.0.0:5000"
