[log]
dir = ".log_tail"

[replication]
server_addr = "0.0.0.0:4003"
upstream_addr = "0.0.0.0:4002"

[frontend]
server_addr = "0.0.0.0:4004"

[admin]
server_addr = "0.0.0.0:9002"

[management]
management_server_addr = "0.0.0.0:5000"
